#include <stdio.h>

int main()
{
    int a,b;
    scanf("%d%d",&a,&b);
    if(a==1)
    {
        if(b<=20)
        {
            printf("Capricorn\n");
        }
        if(b>20)
        {
            printf("Aquarius\n");
        }
    }
    if(a==2)
    {
        if(b<=18)
        {
            printf("Aquarius\n");
        }
        if(b>18)
        {
            printf("Pisces\n");
        }
    }
    if(a==3)
    {
        if(b<=20)
        {
            printf("Pisces\n");
        }
        if(b>20)
        {
            printf("Aries\n");
        }
    }
    if(a==4)
    {
        if(b<=20)
        {
            printf("Aries\n");
        }
        if(b>20)
        {
            printf("Taurus\n");
        }
    }
    if(a==5)
    {
        if(b<=21)
        {
            printf("Taurus\n");
        }
        if(b>21)
        {
            printf("Gemini\n");
        }
    }
    if(a==6)
    {
        if(b<=21)
        {
            printf("Gemini\n");
        }
        if(b>21)
        {
            printf("Cancer\n");
        }
    }
    if(a==7)
    {
        if(b<=22)
        {
            printf("Cancer\n");
        }
        if(b>22)
        {
            printf("Leo\n");
        }
    }
    if(a==8)
    {
        if(b<=23)
        {
            printf("Leo\n");
        }
        if(b>23)
        {
            printf("Virgo\n");
        }
    }
    if(a==9)
    {
        if(b<=23)
        {
            printf("Virgo\n");
        }
        if(b>23)
        {
            printf("Libra\n");
        }
    }
    if(a==10)
    {
        if(b<=23)
        {
            printf("Libra\n");
        }
        if(b>23)
        {
            printf("Scorpio\n");
        }
    }
    if(a==11)
    {
        if(b<=22)
        {
            printf("Scorpio\n");
        }
        if(b>22)
        {
            printf("Sagittarius\n");
        }
    }
    if(a==12)
    {
        if(b<=21)
        {
            printf("Sagittarius\n");
        }
        if(b>21)
        {
            printf("Capricorn\n");
        }
    }
}
